### ISSUE TITLE
Potential bug from #43

### ISSUE THREAD

**Issue by yunhailuo** [IHEC/ihec-ecosystems#51]
We tried to use master branch to validate our potential EpiRR submission and got the following errors:

```bash
[{'-config': './config.json', '-out': 'ENCODE/ENCSR394KIB_samples.validated.xml'}, ['ENCODE/ENCSR394KIB_samples.xml']]
./config.json
Traceback (most recent call last):
  File "__main__.py", line 46, in <module>
    main(Config.sys())
  File "__main__.py", line 33, in main
    validate_sample.main(args)
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_sample.py", line 47, in main
    ihec_validators = cmn.safedict([(schema["version"] ,  JsonSchema(schema["schema"], args)) for schema in config["ihec"]["sample"]])
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_json.py", line 53, in __init__
    e['$ref'] = self.fixfilebase(e['$ref'])
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_json.py", line 17, in fixfilebase
    assert f.startswith(self.expectedpath), [f, self.expectedpath]
AssertionError: [u'file:../schemas/json/sample.json#/definitions/cell_line', 'file:schema/']
[{'-config': './config.json', '-out': 'ENCODE/ENCSR394KIB_experiment.validated.xml'}, ['ENCODE/ENCSR394KIB_experiment.xml']]
./config.json
Traceback (most recent call last):
  File "__main__.py", line 46, in <module>
    main(Config.sys())
  File "__main__.py", line 35, in main
    validate_experiment.main(args) 
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_experiment.py", line 63, in main
    ihec_validators = cmn.safedict([(schema["version"] ,  JsonSchema(schema["schema"], args)) for schema in config["ihec"]["experiment"]])
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_json.py", line 58, in __init__
    e['$ref'] = self.fixfilebase(e['$ref'])
  File "/Users/yunhailuo/Github/ihec-ecosystems/version_metadata/validate_json.py", line 17, in fixfilebase
    assert f.startswith(self.expectedpath), [f, self.expectedpath]
AssertionError: [u'file:../schemas/json/experiment.json#/definitions/chromatin_accessibility', 'file:schema/']
Done!
```

Looking into the code, I think the error is related to this line in `validate_json.py`:
https://github.com/IHEC/ihec-ecosystems/blob/168713a84fa025fcf347ff026500ab874fb0edf7/version_metadata/validate_json.py#L49

The directory structure for schemas has been changed in #43. It seems the `self.expectedpath` should be `'file:../schemas/json/'` rather than `'file:schema/'`. Otherwise, the code would only see the new path and fail the assertion while fixing file base:
https://github.com/IHEC/ihec-ecosystems/blob/168713a84fa025fcf347ff026500ab874fb0edf7/version_metadata/validate_json.py#L17

Our submission would pass validation locally after making that single line change. I can PR if needed.

**Comment by dzerbino** [comment]
D'oh, that would be my fault!

Could you please PR?

**Comment by yunhailuo** [comment]
@dzerbino Thanks for checking. PRed in #52

**Comment by sitag** [comment]
@yunhailuo @yunhailuo merged.
